name: build
on:
  push:
    branches:
      - master
    tags:
      - v*
permissions:
  packages: write
jobs:
  container:
    uses: greboid/.github/.github/workflows/docker.yml@master
    secrets: inherit
